server:
  port: 8080
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true    
#    hibernate:
#      ddl-auto: update      
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
client:
  url:
    cpf-validator: https://user-info.herouapp.com/users/
#client:
#  applicationName: APP
#  url:
#    cep: https://viacep.com.br/ws

swagger:
  base-package: com.cwi.cooperative.voting
  title: Cooperative Voting System API REST
  description: Descrive of service 
  version: 1.0
  terms: Terms of Service
  develloper-name: Ricardo Spinoza
  develloper-email: ricardospinoza@gmail.com
  licence: Apache License Version 2.0
  licence-url: https://www.apache.org/licesen.html
